mins: {pot1: 240.987, pot2: 349.6, pot3: 240.987, pot4: 349.6, pot5: 240.987, pot6: 349.6,
  pot7: 0.0, pot8: 0.0}
range: 188


rosdistro: 'melodic

  '
roslaunch:
  uris: {host_robothand_hp_elitebook_840_g1__35523: 'http://robothand-HP-EliteBook-840-G1:35523/',
    host_robothand_hp_elitebook_840_g1__39951: 'http://robothand-HP-EliteBook-840-G1:39951/'}
rosversion: '1.14.13

  '
run_id: 5063ba5c-f0dd-11ec-9410-2babb065445d
serial_node: {baud: 9600, port: /dev/ttyACM0}
